classDiagram
    class MainMenu {
        -_startButton: Button
        -_settingsButton: Button
        
        -StartGame() void
        -OpenSettings() void
    }
    
    class WorldEntity {
        <<abstract>>
        
        -Direction: Direction
        +?Name: string
        
        +?Interact(PlayerEntity) void
    }
    
    class PlayerEntity {
        -Move() void
        +Interact() void
        +OpenSettings() void
    }
    
    class Direction {
        <<enumeration>>
        North
        East,
        South,
        West
    }
    